INSERT INTO tags (tag_value) VALUES ('spring');
INSERT INTO tags (tag_value) VALUES ('java');
INSERT INTO tags (tag_value) VALUES ('core');
INSERT INTO tags (tag_value) VALUES ('hibernate');
INSERT INTO tags (tag_value) VALUES ('sql');
INSERT INTO tags (tag_value) VALUES ('data');
INSERT INTO tags (tag_value) VALUES ('kafka');
INSERT INTO tags (tag_value) VALUES ('security');
INSERT INTO tags (tag_value) VALUES ('bean');
INSERT INTO tags ( tag_value) VALUES ('js');

INSERT INTO posts (post_title, post_content) VALUES ('java talk', 'we going to talk about java core' );
INSERT INTO posts (post_title, post_content) VALUES ('spring security', 'to configure spring security just use java and beans' );
INSERT INTO posts (post_title, post_content) VALUES ('spring sql', 'data storage and spring sql' );
INSERT INTO posts (post_title, post_content) VALUES ('spring core', 'bean is main thing in spring core' );
INSERT INTO posts (post_title, post_content) VALUES ('hibernate talk', 'hibernate is powerful jpa specification for spring to deal with sql data' );

INSERT INTO posts_tags (post_id, tag_id) VALUES ( 1, 2 );
INSERT INTO posts_tags (post_id, tag_id) VALUES ( 1, 3 );
INSERT INTO posts_tags (post_id, tag_id) VALUES ( 2, 1 );
INSERT INTO posts_tags (post_id, tag_id) VALUES ( 2, 8 );
INSERT INTO posts_tags (post_id, tag_id) VALUES ( 2, 2 );
INSERT INTO posts_tags (post_id, tag_id) VALUES ( 2, 9 );
INSERT INTO posts_tags (post_id, tag_id) VALUES ( 3, 1 );
INSERT INTO posts_tags (post_id, tag_id) VALUES ( 3, 5 );
INSERT INTO posts_tags (post_id, tag_id) VALUES ( 3, 6 );
INSERT INTO posts_tags (post_id, tag_id) VALUES ( 4, 9 );
INSERT INTO posts_tags (post_id, tag_id) VALUES ( 4, 1 );
INSERT INTO posts_tags (post_id, tag_id) VALUES ( 4, 3 );
INSERT INTO posts_tags (post_id, tag_id) VALUES ( 5, 4 );
INSERT INTO posts_tags (post_id, tag_id) VALUES ( 5, 1 );
INSERT INTO posts_tags (post_id, tag_id) VALUES ( 5, 5 );
INSERT INTO posts_tags (post_id, tag_id) VALUES ( 5, 6 );
